# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#top"
  weight = 10



[[main]]
  name = "About"
  url = "#about"
  weight = 50

[[main]]
  name = "19 Agenda"
  url = "#2019"
  weight = 51

[[main]]
  name = "Subscribe"
  url = "#mailinglist"
  weight = 52

[[main]]
  name = "Organizers"
  url = "#people"
  weight = 70

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 71


[[main]]
  name = "Past Events"
  url = "#experience"
  weight = 75

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
